standalone: true
pdf-engine: xelatex
geometry: margin=2.0cm
highlight-style: pygments
output:
  pdf_document: default

# Hyperrefâ€‘Optionen
colorlinks: true
linkcolor: blue
urlcolor: blue
citecolor: blue
filecolor: blue
anchorcolor: blue

header-includes:
  - \usepackage{array}
  - \setlength{\tabcolsep}{12pt}
  - \renewcommand{\arraystretch}{1.5}
  - \setlength{\extrarowheight}{2pt}
